; Program: TRON
; File: GUI.INC
;
; Author: Jan De Groot <jan.degroot@live.be>
; Author: Khaled Radmal
;
; Copyright 2015 under the Raindrop License Agreement V1.1.
; If you did not receive a copy of the Raindrop License Agreement 
; with this Software, please contact the Author of the Software.
;

extern GUI_Display_SplashScreen:PROC
extern GUI_Update_Player_Position:PROC
extern GUI_Refresh_Field:PROC
extern GUI_Update_Score:PROC
extern GUI_Draw_Obstacle:PROC
extern GUI_Declare_Win:PROC