; Program: TRON
; File: CORE.INC
;
; Author: Jan De Groot <jan.degroot@live.be>
; Author: Khaled Radmal
;
; Copyright 2015 under the Raindrop License Agreement V1.1.
; If you did not receive a copy of the Raindrop License Agreement 
; with this Software, please contact the Author of the Software.
;

extern Core_Move_Players:PROC
extern Core_Check_Collision:PROC
extern Core_Start_Game:PROC
extern Core_New_Game:PROC
extern Core_New_Match:PROC
extern Core_End_Match:PROC
extern Core_Display_Splash:PROC
extern Core_Place_Obstacle:PROC